src/scrcaca.c: move from deprecated cucul_* names to caca_* names
Most recent libcaca-0.99.beta20 dropped deprecated cucul_* names in:
    https://github.com/cacalabs/libcaca/commit/5f0ec215f8c9915ed028324a8ecac8212f68e18d

This caused the following build failure:

    scrcaca.c:51:5: error: unknown type name 'cucul_canvas_t'; did you mean 'caca_canvas_t'?
       51 |     cucul_canvas_t *cv; caca_display_t *dp; caca_event_t ev;

The change moves away from cucul_* names.